# frozen_string_literal: true

source "https://rubygems.org"

gem 'jekyll', '~> 4.3.0'
gem 'jekyll-theme-cayman'
gem 'jekyll-seo-tag', '~> 2.0'
gem 'json', '~> 2.7.0'
gem 'sass-embedded', '~> 1.58.0'
gem 'html-proofer', '~> 3.19'
gem 'rubocop-github', '~> 0.26'
gem 'w3c_validators', '~> 1.3'
